name: Go CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Download Go modules
      run: go mod download

    - name: Build
      run: go build .

    - name: Run Go tests
      run: go test -v ./...

    - name: Run Go vet
      run: go vet ./...

